name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve? Why do you want it?
      placeholder: "I often find myself wanting to... / It's frustrating when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "Add a button that... / Show a tooltip when..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other ways to solve this?
      placeholder: "I also considered... but that wouldn't work because..."

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area of the game does this affect?
      options:
        - Gameplay / Mechanics
        - User Interface
        - Quality of Life
        - Accessibility
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in implementing this yourself?
      options:
        - label: I would be willing to implement this feature
