extends GutTest
## EE-9 · REACTIVE-POLICY SWEEP (Pip 2026-07-14, WORKSHOP_2_BACKLOG "Balance-instrument
## roadmap" + "#638 review rulings").
##
## Runs the named REACTIVE policies (SweepPolicies.all — declarative condition->action rules,
## parameterized documentation of theorized play) x deterministic seeds through the SAME month
## driver as the calibration harness (l1_month_driver.gd, extracted from test_l1_month_sweep.gd
## — one driver, two policy front-ends). Reports months-survived distributions, the EE-8
## root-cause breakdown, and the T9 floor status (measured, never gated here).
##
## Relationship to the calibrator (test_l1_month_sweep.gd): that file's 72-run table on ITS
## policy set (do_nothing/safety_lean/random_walk/...) is the calibration reference
## (docs/balance/L1_CALIBRATION_2026-07-14.md). This sweep tests LINES — reactive strategy
## outlines like fundraise_first — against the same engine + driver. `passive` here matches
## do_nothing's shape (empty plans, ignore windows) as the cross-harness anchor.
##
## Lives in tests/manual so CI/quick does NOT run it. Invoke:
##   "/c/Program Files/Godot/Godot_v4.5.1-stable_win64_console.exe" --headless \
##     -s res://addons/gut/gut_cmdln.gd -gdir=res://tests/manual \
##     -gselect=test_policy_sweep.gd -glog=1 -gexit
##
## CAVEAT: constants are the DIALS-1-4 CALIBRATION (L1_CALIBRATION_2026-07-14) now running on
## NINE-STREAM DOOM (ADR-0015 / #643). The dial-5 Attention pass is still pending, and the
## calibration dials were tuned pre-stream (a re-calibration on stream doom is owed). The
## FRAMEWORK is the durable deliverable; re-run whenever constants move (one command, footer).

const RP = preload("res://tests/manual/reactive_policy.gd")
const Driver = preload("res://tests/manual/l1_month_driver.gd")
const Adapter = preload("res://tests/manual/reactive_adapter.gd")
const SweepPoliciesC = preload("res://tests/manual/sweep_policies.gd")

const NUM_SEEDS := 8
const REPORT_PATH := "res://../docs/balance/POLICY_SWEEP.md"

# The "standard lines" the T9 floor applies to (Pip #638: no standard run < 6 months; the
# carried exploit-sweep dispositions passive/.../loan_hoard are deliberately degenerate probes,
# but loan-taking aggressive-but-legal play counts as standard per the memo's T9 note).
const STANDARD_LINES := ["fundraise_first", "balanced_operator", "scout_heavy", "loan_desperation_reactive"]
const T9_FLOOR_MONTHS := 6

# Cross-harness anchor from docs/balance/L1_CALIBRATION_2026-07-14.md (the memo's headline).
const MEMO_DO_NOTHING_MEDIAN := 14.0


func _seeds() -> Array:
	var a := []
	for i in range(NUM_SEEDS):
		a.append("sweep-%02d" % i)  # exploit-sweep seed naming, for continuity
	return a


func _median(vals: Array) -> float:
	var s := vals.duplicate()
	s.sort()
	var n := s.size()
	if n == 0:
		return 0.0
	if n % 2 == 1:
		return float(s[n / 2])
	return (float(s[n / 2 - 1]) + float(s[n / 2])) / 2.0


func test_policy_sweep() -> void:
	var policies: Array = SweepPoliciesC.all()
	var by_policy := {}
	var t0 := Time.get_ticks_msec()
	for policy in policies:
		by_policy[policy.name] = []
		for seed in _seeds():
			by_policy[policy.name].append(Driver.run(seed, Adapter.new(policy)))
	var elapsed := (Time.get_ticks_msec() - t0) / 1000.0

	# ---- Determinism CSV block (diff across revisions: same seeds -> same deaths) ----
	print("\n===POLICY_SWEEP_RUNS_BEGIN===")
	print("seed,policy,months,death_turn,surface,root_cause,doom_final,money_final")
	for policy in policies:
		for r in by_policy[policy.name]:
			print("%s,%s,%d,%d,%s,%s,%.1f,%d" % [r.seed, r.policy, r.months, r.death_turn,
				r.surface, r.root_cause, r.doom_final, r.money_final])
	print("===POLICY_SWEEP_RUNS_END===")

	var lines := []
	lines.append("# Reactive-Policy Sweep (EE-9) — strategy lines on nine-stream doom")
	lines.append("")
	lines.append("> **Base:** the dials-1-4 calibration (`docs/balance/L1_CALIBRATION_2026-07-14.md`) running on")
	lines.append("> **nine-stream doom** (ADR-0015 / #643). **CAVEAT:** the dial-5 Attention pass is still pending,")
	lines.append("> and the calibration dials were tuned pre-stream — a re-calibration on stream doom is owed, so")
	lines.append("> read ORDERING + deltas, not absolute months. The reactive-policy FRAMEWORK is the durable")
	lines.append("> deliverable; re-run whenever constants move (footer, one command).")
	lines.append("")
	lines.append("Auto-generated by `godot/tests/manual/test_policy_sweep.gd`. %d reactive policies x %d seeds through the SHARED month driver (`l1_month_driver.gd` — the calibration harness's extracted run loop). Deterministic per WS-0; score = months survived." % [policies.size(), NUM_SEEDS])
	lines.append("")
	lines.append("## Headline — months survived")
	lines.append("")
	lines.append("| Policy | median months | min | max | vs do_nothing (14.0) | doom-root | ledger-root | rep-root | survived-to-cap |")
	lines.append("|---|---|---|---|---|---|---|---|---|")

	var medians := {}
	for policy in policies:
		var rows: Array = by_policy[policy.name]
		var months := []
		var rc := {"doom": 0, "ledger": 0, "rep": 0, "other": 0}
		var immortal := 0
		for r in rows:
			months.append(r.months)
			if not r.game_over:
				immortal += 1
			var root: String = String(r.root_cause)
			rc[root if rc.has(root) else "other"] += 1
		months.sort()
		medians[policy.name] = _median(months)
		lines.append("| %s | %.1f | %d | %d | %.2fx | %d | %d | %d | %d |" % [
			policy.name, medians[policy.name], months[0], months[months.size() - 1],
			medians[policy.name] / MEMO_DO_NOTHING_MEDIAN, rc["doom"], rc["ledger"], rc["rep"], immortal])

	# ---- Policy parameter dump (the dials future sweeps vary) ----
	lines.append("")
	lines.append("## Policy parameters (the dials future sweeps vary)")
	lines.append("")
	for policy in policies:
		lines.append("- **%s** — %s" % [policy.name, RP.params_line(policy)])

	# ---- Findings ----
	lines.append("")
	lines.append("## Findings")
	lines.append("")

	# T9 floor (measured, not gated — the calibration memo owns the pass/fail story).
	var t9_violations := []
	for policy in policies:
		if not (policy.name in STANDARD_LINES):
			continue
		for r in by_policy[policy.name]:
			if r.game_over and int(r.months) < T9_FLOOR_MONTHS:
				t9_violations.append("`%s` seed `%s` died at month %d (%s / root %s)" % [
					r.policy, r.seed, r.months, r.surface, r.root_cause])
	if t9_violations.is_empty():
		lines.append("- **T9 floor HOLDS for the reactive lines** — no standard-line run (%s) died before month %d. Extends the memo's T9 result (measured there on the calibrator's policy set) to the strategy-line set." % [", ".join(STANDARD_LINES), T9_FLOOR_MONTHS])
	else:
		lines.append("- **T9 floor violations on the reactive lines** (%d/%d standard-line runs; the memo's T9 was measured on the CALIBRATOR's policy set, so new lines can find new holes):" % [t9_violations.size(), STANDARD_LINES.size() * NUM_SEEDS])
		for v in t9_violations:
			lines.append("  - %s" % v)

	# fundraise_first vs the naive-loans foil.
	var ff: float = medians.get("fundraise_first", 0.0)
	var ld: float = medians.get("loan_desperation_reactive", 0.0)
	lines.append("- **fundraise_first vs loan_desperation_reactive** — median months %.1f vs %.1f (%+.1f). %s" % [
		ff, ld, ff - ld,
		("Fundraise-by-default outlasts reach-for-loans, as theorized — the expected-player finance pattern is the better line." if ff > ld
		else "Naive loans match/beat fundraise-first — finance tuning question for the L5 lane.")])

	# Cross-harness anchor.
	lines.append("- **Cross-harness anchor** — `passive` (empty plans, ignore windows) median %.1f vs the calibrator's do_nothing 14.0. Same driver, same constants; residual gap = seed-set + window-arrival differences (n=8, sigma 2-3 months per the memo's variance note)." % medians.get("passive", 0.0))

	lines.append("")
	lines.append("_Sweep ran in %.1fs. Regenerate: `\"$GODOT\" --headless -s res://addons/gut/gut_cmdln.gd -gdir=res://tests/manual -gselect=test_policy_sweep.gd -gexit` (from `godot/`)._" % elapsed)

	var text := "\n".join(lines) + "\n"
	var f = FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if f:
		f.store_string(text)
		f.close()

	print("\n===POLICY_SWEEP_REPORT_BEGIN===")
	print(text)
	print("===POLICY_SWEEP_REPORT_END===")

	# Instrument-correctness assertions ONLY (T9 is a reported measurement, not a gate here).
	for policy in policies:
		assert_eq((by_policy[policy.name] as Array).size(), NUM_SEEDS, "%s ran all seeds" % policy.name)
