extends GutTest
## EE-9 · L1 MONTH SWEEP — reactive-policy balance instrument (Pip 2026-07-14).
##
## Runs the named reactive policies (SweepPolicies.all) x deterministic seeds through the REAL L1
## month loop (MonthRunner: plan phase -> day-tick playback -> window auto-pause -> month boundary),
## and reports per policy: MONTHS-survived distribution, the surface OUTCOME breakdown, the EE-8
## ROOT-CAUSE breakdown, and the T9 floor check (no standard-policy run should die < 6 months).
##
## This is the month-grain sibling of tests/manual/test_exploit_sweep.gd (turn-grain, kept
## untouched as its own regression reference). The policies are DECLARATIVE reactive rules
## (ReactivePolicy) — documentation of theorized play whose parameters future sweeps can vary.
##
## Lives in tests/manual so `run_godot_tests.py --quick`/CI does NOT run it. Invoke:
##   "/c/Program Files/Godot/Godot_v4.5.1-stable_win64_console.exe" --headless \
##     -s res://addons/gut/gut_cmdln.gd -gdir=res://tests/manual \
##     -gselect=test_l1_month_sweep.gd -glog=1 -gexit
##
## CAVEAT (read before trusting any number): current main's balance CONSTANTS predate the
## imminent nine-stream doom migration (WORKSHOP_2_BACKLOG DQ-21). The FRAMEWORK is the durable
## deliverable; the mined numbers get re-run post-migration (cheap — one command, see the footer).

const RP = preload("res://tests/manual/reactive_policy.gd")
const MonthRunnerC = preload("res://tests/manual/month_runner.gd")
const SweepPoliciesC = preload("res://tests/manual/sweep_policies.gd")

const NUM_SEEDS := 8
const MAX_MONTHS := 24
const REPORT_PATH := "res://../docs/balance/L1_MONTH_SWEEP.md"

# The "standard lines" the T9 floor applies to (must not die < 6 months). The carried baselines
# (passive/…/loan_hoard) are deliberately degenerate and exempt.
const STANDARD_LINES := ["fundraise_first", "balanced_operator", "scout_heavy", "loan_desperation"]
const T9_FLOOR_MONTHS := 6


func _seeds() -> Array:
	var a := []
	for i in range(NUM_SEEDS):
		a.append("sweep-%02d" % i)  # reuse the exploit-sweep seed naming for continuity
	return a


func _median(sorted_vals: Array) -> float:
	var n := sorted_vals.size()
	if n == 0:
		return 0.0
	if n % 2 == 1:
		return float(sorted_vals[n / 2])
	return (float(sorted_vals[n / 2 - 1]) + float(sorted_vals[n / 2])) / 2.0


func test_l1_month_sweep() -> void:
	var policies: Array = SweepPoliciesC.all()
	var by_policy := {}
	for p in policies:
		by_policy[p.name] = []
	var t0 := Time.get_ticks_msec()
	for policy in policies:
		for seed in _seeds():
			by_policy[policy.name].append(MonthRunnerC.run(seed, policy, {"max_months": MAX_MONTHS}))
	var elapsed := (Time.get_ticks_msec() - t0) / 1000.0

	# ---- Determinism CSV block (diff across revisions to prove instrumentation is outcome-neutral) ----
	print("\n===MONTH_SWEEP_RUNS_BEGIN===")
	print("seed,policy,months,turns,outcome,doom,root_cause")
	for policy in policies:
		for r in by_policy[policy.name]:
			print("%s,%s,%d,%d,%s,%.2f,%s" % [r.seed, r.policy, r.months, r.turns, r.outcome, r.doom, r.root_cause])
	print("===MONTH_SWEEP_RUNS_END===")

	var lines := []
	lines.append("# L1 Month Sweep — reactive-policy balance instrument")
	lines.append("")
	lines.append("> **CAVEAT — regenerate, don't trust the absolutes.** Current main's balance constants")
	lines.append("> predate the nine-stream doom migration (WORKSHOP_2_BACKLOG DQ-21). The reactive-policy")
	lines.append("> FRAMEWORK is the durable deliverable; these numbers get re-run post-migration. One command,")
	lines.append("> see the footer. Read trends and deltas, not absolute month counts.")
	lines.append("")
	lines.append("Auto-generated by `godot/tests/manual/test_l1_month_sweep.gd`. %d reactive policies x %d seeds through the real L1 month loop (max %d plan-months). Deterministic per WS-0; score = months survived (ADR-0002 turns, re-denominated to months)." % [policies.size(), NUM_SEEDS, MAX_MONTHS])
	lines.append("")
	lines.append("## Headline — survival")
	lines.append("")
	lines.append("> Deaths are currently SUB-MONTH (doom reaches 100 in ~4-10 day-ticks under pre-migration")
	lines.append("> constants), so `months` is coarse today — the turn columns carry the live signal and are")
	lines.append("> the pre-migration regression reference. Post-rebalance the month columns become the story.")
	lines.append("")
	lines.append("| Policy | median months | median turns | min turns | max turns | survived-to-cap | doom deaths | ledger deaths | median doom |")
	lines.append("|---|---|---|---|---|---|---|---|---|")

	var medians := {}
	var turn_medians := {}
	for policy in policies:
		var rows: Array = by_policy[policy.name]
		var months := []
		var turns := []
		var dooms := []
		var c := {"win": 0, "doom_loss": 0, "ledger_death": 0, "survived": 0, "other_loss": 0}
		for r in rows:
			months.append(r.months)
			turns.append(r.turns)
			dooms.append(r.doom)
			c[r.outcome] = int(c.get(r.outcome, 0)) + 1
		months.sort()
		turns.sort()
		dooms.sort()
		medians[policy.name] = _median(months)
		turn_medians[policy.name] = _median(turns)
		lines.append("| %s | %.1f | %.1f | %d | %d | %d | %d | %d | %.1f |" % [
			policy.name, medians[policy.name], turn_medians[policy.name], turns[0], turns[turns.size() - 1],
			c["survived"], c["doom_loss"], c["ledger_death"], _median(dooms)])

	# ---- Root-cause attribution (EE-8, ADR-0012) ----
	lines.append("")
	lines.append("## Root-cause attribution (EE-8, ADR-0012)")
	lines.append("")
	lines.append("| Policy | root: ledger | root: doom | root: rep | root: other/none |")
	lines.append("|---|---|---|---|---|")
	for policy in policies:
		var rc := {"ledger": 0, "doom": 0, "rep": 0, "other": 0}
		for r in by_policy[policy.name]:
			var root: String = String(r.root_cause)
			if not rc.has(root):
				root = "other"
			rc[root] += 1
		lines.append("| %s | %d | %d | %d | %d |" % [policy.name, rc["ledger"], rc["doom"], rc["rep"], rc["other"]])

	# ---- Policy parameter dump (documents the tunables future sweeps vary) ----
	lines.append("")
	lines.append("## Policy parameters (the dials future sweeps vary)")
	lines.append("")
	for policy in policies:
		lines.append("- **%s** — %s" % [policy.name, RP.params_line(policy)])

	# ---- Findings ----
	lines.append("")
	lines.append("## Findings")
	lines.append("")

	# T9 floor: no standard line should die before month 6.
	var t9_violations := []
	for policy in policies:
		if not (policy.name in STANDARD_LINES):
			continue
		for r in by_policy[policy.name]:
			if r.outcome != "survived" and r.months < T9_FLOOR_MONTHS:
				t9_violations.append("`%s` seed `%s` died at month %d (%s / root %s)" % [r.policy, r.seed, r.months, r.outcome, r.root_cause])
	if t9_violations.is_empty():
		lines.append("- **T9 floor HOLDS** — no standard-line run (%s) died before month %d." % [", ".join(STANDARD_LINES), T9_FLOOR_MONTHS])
	else:
		lines.append("- **T9 floor VIOLATED (expected, pre-migration)** — %d/%d standard-line runs died before month %d, all to sub-month doom (doom hits 100 in ~4-10 day-ticks). This is the DQ-8/DQ-13 'doom too hot' state the nine-stream migration exists to fix; it is a *reported measurement*, not a test failure. Regenerate post-migration — the T9 floor is the acceptance target then." % [t9_violations.size(), STANDARD_LINES.size() * NUM_SEEDS, T9_FLOOR_MONTHS])

	# fundraise_first vs loan_desperation: does fundraising-first beat naive loans? (turn grain,
	# since everything currently dies in month 1).
	var ff_med: float = turn_medians.get("fundraise_first", 0.0)
	var ld_med: float = turn_medians.get("loan_desperation", 0.0)
	lines.append("- **fundraise_first vs loan_desperation** — median turns %.1f vs %.1f. %s" % [
		ff_med, ld_med,
		("fundraise-first outlasts naive loans (as theorized)." if ff_med > ld_med
		else ("naive loans match/beat fundraise-first — but both die sub-month to doom, so finance choice is currently moot; revisit post-migration." if ld_med >= ff_med else ""))])

	# Passive baseline reference (turn grain).
	lines.append("- **Passive (do-nothing) reference** — median %.1f turns to a doom death. Every policy currently dies to doom before finance strategy can matter; the finance lines diverge only once doom stops being sub-month-lethal." % turn_medians.get("passive", 0.0))

	lines.append("")
	lines.append("_Sweep ran in %.1fs. Regenerate: `\"$GODOT\" --headless -s res://addons/gut/gut_cmdln.gd -gdir=res://tests/manual -gselect=test_l1_month_sweep.gd -gexit` (from `godot/`)._" % elapsed)

	var text := "\n".join(lines) + "\n"
	var f = FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if f:
		f.store_string(text)
		f.close()

	print("\n===MONTH_SWEEP_REPORT_BEGIN===")
	print(text)
	print("===MONTH_SWEEP_REPORT_END===")

	# Instrument-correctness assertions ONLY. The T9 floor is a REPORTED balance measurement
	# (violated pre-migration by design), not a pass/fail gate — asserting it here would conflate
	# 'the instrument works' with 'the game is balanced'. The floor becomes an acceptance target
	# once the doom migration lands; until then the finding above carries it.
	assert_eq(by_policy[policies[0].name].size(), NUM_SEEDS, "sweep ran all seeds for each policy")
	for policy in policies:
		assert_eq((by_policy[policy.name] as Array).size(), NUM_SEEDS, "%s ran all seeds" % policy.name)
