"""Generate docs/game-design/decisions/README.md from the ADR files themselves.

WHY THIS EXISTS. The hand-kept decisions/README.md is the exact failure mode the DQ
index was built to kill -- generate_dq_index.py's own docstring cites it by name:
"see the stale decisions/README.md for the failure mode this avoids". It then went
stale anyway: as of the 2026-08-03 ADR/DQ audit it was missing ADR-0018 entirely and
carried pre-amendment statuses for 0011, 0015 and 0018, last really touched 07-25.

The audit demonstrated the argument in a single run: the GENERATED DQ index
regenerated BYTE-IDENTICAL (zero drift) while the HAND-MAINTAINED ADR index had
rotted. Same repo, same period, same maintainer. That is the whole case.

Aligns with open issues #1018 (progressive supersession scan, required frontmatter,
a generated README gated in pre-commit) and #1049 (correctness/staleness pass with an
implementation-status field the website can render). This is the minimal generator
those can grow from, not a competing scheme.

Usage:
    python scripts/generate_adr_index.py          # (re)write the index
    python scripts/generate_adr_index.py --check  # exit 1 if the index is stale

Parses, per ADR file:
    # ADR-NNNN -- <title>              the H1
    - **Status:** <text>               the ADR-TEMPLATE.md contract
    - **Date:** <text>
    ## Amendment ... <date>            surfaced as an "Amended" column, so a
                                       post-hoc ruling is visible at the index
                                       without anyone editing the Status line

DELIBERATE: a missing Status line is a hard ERROR, not a blank cell. That enforces
template conformance on every future ADR for free, and a silently blank status is
precisely the class of wrong-looking-right this repo keeps paying for (#1027).

NOT DECIDED HERE, and left to Pip (audit section 5): whether docs/adr/ -- a SECOND
ADR series whose numbers collide with this one, and whose ADR-0002 contradicts this
series' ADR-0002 on whether victory exists (#809) -- should be folded in, renamed, or
indexed separately. This generator reads ONLY the design series and WARNS that the
other exists, rather than quietly pretending it does not.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "docs" / "game-design" / "decisions"
OUT = SRC_DIR / "README.md"
OTHER_SERIES = ROOT / "docs" / "adr"

# Older ADRs use an em-dash in the H1; newer ones use "--". The ASCII hook runs
# INCREMENTALLY (changed files only), so both spellings are legitimately in tree.
H1 = re.compile(r"^#\s+(ADR-(\d+))\s*(?:--|--|--)\s*(.+?)\s*$", re.M)
STATUS = re.compile(r"^-\s+\*\*Status:\*\*\s*(.+?)\s*$", re.M)
DATE = re.compile(r"^-\s+\*\*Date:\*\*\s*(.+?)\s*$", re.M)
AMENDMENT = re.compile(r"^##\s+Amendment\b(.*)$", re.M)
ISO_DATE = re.compile(r"(\d{4}-\d{2}-\d{2})")
# Optional. When absent the summary column falls back to the first sentence of
# ## Context. An explicit Summary is strongly preferred, because it lives NEXT TO
# THE DECISION and is therefore maintained by whoever changes the decision -- which
# is the entire reason to generate this index rather than curate it separately.
SUMMARY = re.compile(r"^-\s+\*\*Summary:\*\*\s*(.+?)\s*$", re.M)
CONTEXT = re.compile(r"^##\s+Context\s*$(.+?)^##\s", re.M | re.S)

# The emitted file must be ASCII (enforce-standards + no-emoji hooks). Mirrors the
# DQ generator's map rather than inventing a second one.
# Keys are built with chr() DELIBERATELY. Written as literal characters this file
# would itself be non-ASCII -- rejected by the very hook it exists to serve. Written
# as backslash-u escapes, black UNESCAPES them back to literals on the next commit
# (observed 2026-08-03). chr() is the only spelling that survives the formatter.
ASCII_MAP = {
    chr(0x00B7): "-",  # middle dot
    chr(0x2013): "--",  # en dash
    chr(0x2014): "--",  # em dash
    chr(0x2018): "'",  # left single quote
    chr(0x2019): "'",  # right single quote
    chr(0x201C): '"',  # left double quote
    chr(0x201D): '"',  # right double quote
    chr(0x2026): "...",  # ellipsis
    chr(0x2192): "->",  # right arrow
    chr(0x2193): "(down)",  # down arrow
    chr(0x226A): "<<",  # much less than
    chr(0x2260): "!=",  # not equal
    chr(0x00A7): "section",
    chr(0x00A0): " ",  # nbsp
}


def to_ascii(text: str) -> str:
    for src, dst in ASCII_MAP.items():
        text = text.replace(src, dst)
    return "".join(c if ord(c) < 128 else "?" for c in text)


STATUS_KEYWORDS = (
    "SUPERSEDED",
    "REJECTED",
    "ACCEPTED",
    "PROPOSED",
    "DRAFT",
)


def short_status(raw: str) -> str:
    """Collapse to the leading status KEYWORD; keep the qualifier as a separate flag.

    The statuses in tree are prose, not tokens -- 'ACCEPTED, as amended by ADR-0004',
    'ACCEPTED as design; build **third**, strictly after ADR-0003 and ADR-0004',
    'DRAFT (formal confirm at 2026-07-27 R3a block)'. Splitting on '(' alone left 19
    ADRs with 7 distinct 'statuses', which makes the tally meaningless -- an index
    whose summary line cannot be read at a glance has failed at its one job.

    Returns (keyword, qualified) where qualified marks that detail was dropped, so
    the index can say so rather than silently flattening it.
    """
    upper = raw.upper()
    for kw in STATUS_KEYWORDS:
        if upper.lstrip().startswith(kw):
            rest = raw.strip()[len(kw) :].strip(" ,;:.-")
            return kw, bool(rest)
    token = raw.split("(")[0].strip().rstrip(".,;:")
    return (token or raw.strip()), False


def parse(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")

    h1 = H1.search(text)
    if not h1:
        raise SystemExit(
            "ERROR: %s has no '# ADR-NNNN -- title' H1. See ADR-TEMPLATE.md." % path.name
        )

    status_m = STATUS.search(text)
    if not status_m:
        raise SystemExit(
            "ERROR: %s has no '- **Status:**' line. Every ADR must declare one "
            "(ADR-TEMPLATE.md:3); a blank status is worse than a wrong one." % path.name
        )

    status_kw, status_qual = short_status(status_m.group(1))
    status_kw = to_ascii(status_kw)

    date_m = DATE.search(text)
    summary = ""
    sm = SUMMARY.search(text)
    if sm:
        summary = sm.group(1)
    else:
        cm = CONTEXT.search(text)
        if cm:
            body = " ".join(cm.group(1).split())
            cut = body.find(". ")
            summary = (body[: cut + 1] if cut > 0 else body)[:200]

    amendments = AMENDMENT.findall(text)
    amend_dates = []
    for tail in amendments:
        found = ISO_DATE.search(tail)
        amend_dates.append(found.group(1) if found else "yes")

    return {
        "id": h1.group(1),
        "num": int(h1.group(2)),
        "title": to_ascii(h1.group(3)),
        "status": status_kw,
        "status_qualified": status_qual,
        "date": to_ascii(date_m.group(1).strip()) if date_m else "--",
        "amended": ", ".join(amend_dates) if amend_dates else "",
        "summary": to_ascii(summary),
        "has_explicit_summary": bool(sm),
        "file": path.name,
    }


def collect() -> list[dict]:
    if not SRC_DIR.is_dir():
        raise SystemExit("ERROR: %s does not exist" % SRC_DIR)
    records = [parse(p) for p in sorted(SRC_DIR.glob("ADR-*.md")) if p.name != "ADR-TEMPLATE.md"]
    if not records:
        raise SystemExit("ERROR: no ADR files found in %s" % SRC_DIR)
    return sorted(records, key=lambda r: r["num"])


def render() -> str:
    rows = collect()
    lines = [
        "# Architecture decision records (GENERATED -- do not hand-edit)",
        "",
        "> Derived from the ADR files in this directory by",
        "> `scripts/generate_adr_index.py`. Regenerate with:",
        "> `python scripts/generate_adr_index.py`. A pre-commit check fails",
        "> commits that change an ADR without regenerating this file.",
        ">",
        "> This index went stale by hand twice before it was generated (missing",
        "> ADR-0018, pre-amendment statuses) -- see the 2026-08-03 ADR/DQ audit.",
        "> **Trust the ADR files themselves for anything load-bearing.**",
        "",
        "| ADR | Title | Status | Date | Amended | Summary |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            "| [%s](%s) | %s | %s | %s | %s | %s |"
            % (
                r["id"],
                r["file"],
                r["title"],
                r["status"] + (" *" if r["status_qualified"] else ""),
                r["date"],
                r["amended"],
                r["summary"],
            )
        )
    lines.append("")

    by_status: dict[str, int] = {}
    for r in rows:
        by_status[r["status"]] = by_status.get(r["status"], 0) + 1
    tally = ", ".join("%d %s" % (n, s) for s, n in sorted(by_status.items()))
    amended = sum(1 for r in rows if r["amended"])
    derived = sum(1 for r in rows if not r["has_explicit_summary"])
    qualified = sum(1 for r in rows if r["status_qualified"])
    lines.append("Total: %d ADRs -- %s. %d carry amendments." % (len(rows), tally, amended))
    if qualified:
        lines.append("")
        lines.append(
            "`*` marks a status carrying a qualifier that this index drops "
            '(%d of them, e.g. "ACCEPTED as design; build third"). Read the ADR '
            "for the condition -- the qualifier is often the load-bearing part." % qualified
        )
    if derived:
        lines.append("")
        lines.append(
            "%d summaries are DERIVED from the first sentence of Context. Add a "
            "`- **Summary:**` line to an ADR to control its wording; the summary then "
            "lives with the decision and is maintained by whoever changes it." % derived
        )
    lines.append("")

    if OTHER_SERIES.is_dir():
        others = sorted(p.name for p in OTHER_SERIES.glob("*.md"))
        if others:
            lines += [
                "## A second ADR series exists, and its numbers collide",
                "",
                "`docs/adr/` holds %d further record(s) not indexed here: %s."
                % (len(others), ", ".join("`%s`" % o for o in others)),
                "",
                "The two series share numbers, and their respective ADR-0002s give",
                "OPPOSITE answers on whether the game has a victory condition (#809).",
                "This generator reads only the design series rather than silently",
                "merging two schemes. Resolving the collision -- fold in, rename to an",
                "ENG- prefix, or index separately -- is an open call (#1018).",
                "",
            ]
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print("decisions/README.md is stale. Run: python scripts/generate_adr_index.py")
            return 1
        return 0
    OUT.write_text(content, encoding="utf-8", newline="\n")
    print("Wrote %s" % OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
