#!/usr/bin/env python3
"""apply_slot_picks.py -- fold a slot_picker.html export into the TRACKED
selection record, tools/assets/demand/slot_picks.json.

Why a separate store from review_state.json, and why it is not a side-map
------------------------------------------------------------------------
A verdict answers "is this good?" -- taste, per ASSET, written once.
A pick answers "is this THE one this slot uses?" -- selection, per (asset,
SLOT) PAIRING, revisable every patch without the asset changing at all.
The analysis (docs/design/ASSET_PAYLOAD_ANALYSIS_2026-08-06.md) rejected
encoding selection as a verdict (option a) and rejected a `chosen` flag stored
beside the verdict (option b, the shape that silently stranded 75% of verdicts
once already). This file is option (c): selection lives in ONE place, the
demand record, and "good but not chosen" needs NO stored label -- it is simply
the absence of an entry here.

So this file is not a MIRROR of anything. It is the single authority for
"which Library asset does this slot pin", which the demand manifest consumes.
`git diff tools/assets/demand/slot_picks.json` IS the manifest diff.

Guards (the silent-wrongness lesson: every failure in review week LOOKED right)
------------------------------------------------------------------------------
Every incoming pick is validated against a FRESH rebuild of the cluster model:
  - the slot/frame id must still exist
  - the picked file must still be a candidate for that exact slot
  - the picked asset must still hold a `keep` verdict (Library membership)
A pick that fails is REPORTED and NOT written. --check re-runs the same
validation over the whole stored record without an export, so drift (a
regenerated batch, a verdict flipped to discard) surfaces loudly.

Usage:
    python tools/art_review/apply_slot_picks.py DOWNLOAD.json [--dry-run]
    python tools/art_review/apply_slot_picks.py --check
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import slot_model  # noqa: E402

REPO = slot_model.REPO
RECORD = REPO / "tools" / "assets" / "demand" / "slot_picks.json"

HEADER = (
    "GENERATED by tools/art_review/apply_slot_picks.py from a slot_picker.html "
    "export. Do not hand-edit: re-run the picker instead. This is the SELECTION "
    "authority the demand manifest (ADR-0019) consumes -- a pick is a property of "
    "the (asset, slot) pairing, never a verdict on the asset. Losing candidates "
    "stay Library assets that no entry names; nothing is done to them."
)


def index_model():
    clusters, frames, stats = slot_model.build_model()
    idx = {}
    for cl in clusters:
        idx["slot:" + cl.slot_id] = {
            "kind": "slot",
            "dest": cl.dest,
            "stem": cl.stem,
            "draw_px": cl.draw_px,
            "draw_why": cl.draw_why,
            "cands": {c.rel: c for c in cl.candidates},
        }
    for fr in frames:
        idx["frame:" + fr.role_id] = {
            "kind": "frame",
            "dest": "",
            "stem": fr.stem,
            "draw_px": 0,
            "draw_why": "UI source material -- see the frame section",
            "cands": {c.rel: c for c in fr.candidates},
        }
    return idx, stats


def load_record():
    if not RECORD.is_file():
        return {"_comment": HEADER, "slots": {}, "frame_roles": {}}
    data = json.loads(RECORD.read_text(encoding="utf-8"))
    data.setdefault("slots", {})
    data.setdefault("frame_roles", {})
    return data


def write_record(data, stats):
    data["_comment"] = HEADER
    data["_source_stats"] = {
        "verdicts_read": stats["state_entries"],
        "contested_clusters": stats["contested_clusters"],
        "frame_roles": stats["frame_roles"],
    }
    data["slots"] = dict(sorted(data["slots"].items()))
    data["frame_roles"] = dict(sorted(data["frame_roles"].items()))
    RECORD.parent.mkdir(parents=True, exist_ok=True)
    RECORD.write_text(
        json.dumps(data, indent=2, sort_keys=False, ensure_ascii=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def validate(key, entry, idx):
    """Return (ok, problem). Never raises; a bad pick must be LOUD, not fatal."""
    node = idx.get(key)
    if node is None:
        return False, "no such %s in the current model (regenerated batch? stale export?)" % (
            "slot" if key.startswith("slot:") else "frame role"
        )
    src = entry.get("src") or ""
    if src and src not in node["cands"]:
        return False, "picked file is not a candidate for this slot: %s" % src
    if node["kind"] == "slot" and entry.get("status") == "chosen" and not src:
        return False, "slot marked chosen with no source file"
    if node["kind"] == "frame" and entry.get("status") == "chosen":
        t = entry.get("treatment") or ""
        if t not in slot_model.FRAME_TREATMENTS:
            return False, "frame treatment %r not one of %s" % (
                t,
                "/".join(slot_model.FRAME_TREATMENTS),
            )
        if t in ("nineslice", "whole") and not src:
            return False, "treatment %s needs a nominated source master" % t
    return True, ""


def merge(incoming, data, idx):
    added = updated = unchanged = skipped_older = rejected = cleared = 0
    for key in sorted(incoming):
        entry = incoming[key]
        if not isinstance(entry, dict):
            print("BAD  %s (not an object)" % key)
            rejected += 1
            continue
        ok, why = validate(key, entry, idx)
        if not ok:
            print("REJECT %s -- %s" % (key, why))
            rejected += 1
            continue
        node = idx[key]
        bucket = data["slots"] if node["kind"] == "slot" else data["frame_roles"]
        rid = key.split(":", 1)[1]
        cand = node["cands"].get(entry.get("src") or "")
        new = {
            "status": entry.get("status") or "",
            "source_file": entry.get("src") or "",
            "source_asset": cand.asset_id if cand else "",
            "note": entry.get("note") or "",
            "decided_at": entry.get("updated_at") or "",
        }
        if node["kind"] == "slot":
            new["destination"] = node["dest"]
            new["draw_px"] = node["draw_px"]
            new["draw_why"] = node["draw_why"]
        else:
            new["treatment"] = entry.get("treatment") or ""
        old = bucket.get(rid)
        if old is None:
            if not new["status"] and not new["note"]:
                continue
            bucket[rid] = new
            added += 1
            print("ADD  %s -> %s" % (key, new.get("treatment") or new["source_file"] or "(none)"))
            continue
        if (old.get("decided_at") or "") > new["decided_at"]:
            skipped_older += 1
            print("SKIP %s (record is newer: %s)" % (key, old.get("decided_at")))
            continue
        comparable = {k: old.get(k, "") for k in ("status", "source_file", "note", "treatment")}
        if comparable == {k: new.get(k, "") for k in comparable}:
            unchanged += 1
            continue
        if not new["status"] and not new["note"]:
            del bucket[rid]
            cleared += 1
            print("REOPEN %s (pick cleared -- back in the working set)" % key)
            continue
        bucket[rid] = new
        updated += 1
        print(
            "UPD  %s: %s -> %s"
            % (
                key,
                old.get("treatment") or old.get("source_file") or "(none)",
                new.get("treatment") or new["source_file"] or "(none)",
            )
        )
    return added, updated, unchanged, skipped_older, rejected, cleared


def action_check(data, idx, stats):
    problems = 0
    for kind, bucket, prefix in (
        ("slot", data["slots"], "slot:"),
        ("frame role", data["frame_roles"], "frame:"),
    ):
        for rid, rec in sorted(bucket.items()):
            key = prefix + rid
            entry = {
                "src": rec.get("source_file", ""),
                "status": rec.get("status", ""),
                "treatment": rec.get("treatment", ""),
            }
            ok, why = validate(key, entry, idx)
            if not ok:
                print("DRIFT  %s (%s) -- %s" % (key, kind, why))
                problems += 1
    n_slots = len(data["slots"])
    n_frames = len(data["frame_roles"])
    print(
        "\nrecorded: %d/%d contested slots, %d/%d frame roles"
        % (n_slots, stats["contested_clusters"], n_frames, stats["frame_roles"])
    )
    if problems:
        print("%d entry/entries no longer validate against the current model." % problems)
        return 1
    print("every recorded pick still resolves to a live Library candidate.")
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("export", nargs="?", help="slot_picks_export_*.json from the page")
    ap.add_argument(
        "--check", action="store_true", help="validate the stored record, write nothing"
    )
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    idx, stats = index_model()
    data = load_record()

    if args.check or not args.export:
        if not args.check:
            ap.error("give an export file, or --check")
        return action_check(data, idx, stats)

    path = Path(args.export)
    if not path.is_file():
        sys.exit("error: %s not found" % path)
    try:
        incoming = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.exit("error: %s is not valid JSON: %s" % (path, e))
    if not isinstance(incoming, dict):
        sys.exit("error: export must be an object of id -> entry")

    added, updated, unchanged, older, rejected, cleared = merge(incoming, data, idx)
    print(
        "\nadded=%d updated=%d reopened=%d unchanged=%d skipped-older=%d rejected=%d"
        % (added, updated, cleared, unchanged, older, rejected)
    )
    print("review_state.json: UNTOUCHED (%d verdicts, read-only input)" % stats["state_entries"])
    if args.dry_run:
        print("dry-run: %s not written." % RECORD)
        return 0
    if added or updated or cleared:
        write_record(data, stats)
        print("wrote %s" % RECORD)
        print("  -> review it with: git diff tools/assets/demand/slot_picks.json")
    else:
        print("nothing to write.")
    return 1 if rejected else 0


if __name__ == "__main__":
    sys.exit(main())
