name: Auto Copilot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3am UTC

jobs:
  find-issues:
    runs-on: ubuntu-latest
    outputs:
      issues: ${{ steps.set-issues.outputs.issues }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List open issues without PRs
        id: set-issues
        run: |
          issues=$(gh issue list --state open --json number,title | jq -c '[.[] | {number: .number, title: .title}]')
          echo "issues=$issues" >> $GITHUB_OUTPUT

  process-issues:
    needs: find-issues
    runs-on: ubuntu-latest
    strategy:
      matrix:
        issue: ${{fromJson(needs.find-issues.outputs.issues)}}
      # Remove the matrix for serial processing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Trigger Copilot agent for issue
        run: |
          ISSUE_NUMBER="${{ matrix.issue.number }}"
          echo "Processing issue #$ISSUE_NUMBER"
          # Insert your Copilot trigger logic here